version: "3.9"

services:
  shopping_service_db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shopping_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shopping_service_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - personalcook_net

  shopping_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@shopping_service_db:5432/shopping_service_db
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      RECIPE_SERVICE_URL: http://recipe_service:8000/recipes
      SOCIAL_SERVICE_URL: http://social_service:8000
    depends_on:
      - shopping_service_db
    ports:
      - "8004:8000"
    networks:
      - personalcook_net

volumes:
  shopping_service_db_data:

networks:
  personalcook_net:
    external: true
    name: personalcook-net
