{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopping_service.fullname" . }}-config
  labels:
    {{- include "shopping_service.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

